# Generated by Django 4.2.7 on 2025-11-07 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_detalletransferencia_transferencia_and_more'),
        ('authentication', '0002_empleadouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadouser',
            name='deposito',
            field=models.ForeignKey(default=1, help_text='Depósito donde trabaja el empleado', on_delete=django.db.models.deletion.CASCADE, related_name='empleados_usuarios', to='inventario.deposito', verbose_name='Depósito'),
            preserve_default=False,
        ),
    ]
