# Generated by Django 4.2.7 on 2025-11-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_empleadouser_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadouser',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(default='ADMIN', help_text='Rol del usuario en el sistema', max_length=50, verbose_name='Rol'),
        ),
    ]
