# Generated by Django 4.2.7 on 2025-09-24 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cajero',
            field=models.ForeignKey(help_text='Usuario que realizó la venta (admin o empleado cajero)', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Cajero'),
        ),
    ]
