# Generated by Django 4.2.7 on 2025-09-25 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_empleadouser'),
        ('ventas', '0002_alter_venta_cajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='empleado_cajero',
            field=models.ForeignKey(blank=True, help_text='Empleado específico que realizó la venta (solo si es empleado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_como_cajero', to='authentication.empleadouser', verbose_name='Empleado Cajero'),
        ),
    ]
