# Generated by Django 4.2.7 on 2025-10-15 00:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_empleado_cajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventa',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de descuento aplicado por oferta', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento Aplicado'),
        ),
        migrations.AddField(
            model_name='itemventa',
            name='oferta_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la oferta aplicada (si hay)', max_length=200, null=True, verbose_name='Nombre de la Oferta'),
        ),
        migrations.AddField(
            model_name='itemventa',
            name='precio_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio original sin descuento (si aplica oferta)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Original'),
        ),
    ]
