# Generated by Django 5.2.5 on 2025-08-26 23:18

import django.core.validators
import django.db.models.deletion
import empleados.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del depósito (ej: Depósito Central, Sucursal Norte)', max_length=100, verbose_name='Nombre del Depósito')),
                ('direccion', models.CharField(help_text='Dirección completa del depósito', max_length=200, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el depósito está activo', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to=settings.AUTH_USER_MODEL, verbose_name='Supermercado')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'unique_together': {('nombre', 'supermercado')},
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del empleado', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido del empleado', max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(help_text='Correo electrónico único del empleado', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('dni', models.CharField(help_text='DNI del empleado (sin puntos ni espacios)', max_length=8, unique=True, validators=[empleados.models.validate_dni], verbose_name='DNI')),
                ('puesto', models.CharField(choices=[('CAJERO', 'Cajero'), ('REPONEDOR', 'Reponedor')], help_text='Rol del empleado en el supermercado', max_length=20, verbose_name='Puesto')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el empleado está activo', verbose_name='Activo')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('deposito', models.ForeignKey(help_text='Depósito donde trabaja el empleado', on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='empleados.deposito', verbose_name='Depósito')),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to=settings.AUTH_USER_MODEL, verbose_name='Supermercado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'unique_together': {('email', 'supermercado')},
            },
        ),
    ]
