# Generated by Django 5.2.5 on 2025-08-26 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deposito',
            unique_together={('nombre', 'direccion', 'supermercado')},
        ),
        migrations.AddField(
            model_name='deposito',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional del depósito', null=True, verbose_name='Descripción'),
        ),
    ]
