# Generated by Django 4.2.7 on 2025-08-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('empleados', '0002_alter_deposito_unique_together_deposito_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='deposito',
            field=models.ForeignKey(help_text='Depósito donde trabaja el empleado', on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='inventario.deposito', verbose_name='Depósito'),
        ),
        migrations.DeleteModel(
            name='Deposito',
        ),
    ]
