# Generated by Django 4.2.7 on 2025-08-27 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del depósito (ej: Depósito Central, Sucursal Norte)', max_length=100, verbose_name='Nombre del Depósito')),
                ('direccion', models.CharField(help_text='Dirección completa del depósito', max_length=200, verbose_name='Dirección')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del depósito', null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el depósito está activo', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to=settings.AUTH_USER_MODEL, verbose_name='Supermercado')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'unique_together': {('nombre', 'direccion', 'supermercado')},
            },
        ),
    ]
