# Generated by Django 5.2.5 on 2025-09-17 22:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad a Transferir')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Transferencia',
                'verbose_name_plural': 'Detalles de Transferencias',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transferencia', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Transferencia')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('deposito_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='inventario.deposito', verbose_name='Depósito Destino')),
                ('deposito_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='inventario.deposito', verbose_name='Depósito Origen')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-fecha_transferencia'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Movimiento')),
                ('tipo_movimiento', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia entre depósitos'), ('INGRESO', 'Ingreso de mercadería'), ('EGRESO', 'Egreso de mercadería'), ('AJUSTE', 'Ajuste de inventario'), ('VENTA', 'Venta')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(help_text='Cantidad positiva para ingresos, negativa para egresos', verbose_name='Cantidad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el movimiento')),
                ('deposito_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_destino', to='inventario.deposito', verbose_name='Depósito Destino')),
                ('deposito_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_origen', to='inventario.deposito', verbose_name='Depósito Origen')),
                ('detalle_transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.detalletransferencia', verbose_name='Detalle de Transferencia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.transferencia', verbose_name='Transferencia Relacionada')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='detalletransferencia',
            name='transferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.transferencia', verbose_name='Transferencia'),
        ),
        migrations.AlterUniqueTogether(
            name='detalletransferencia',
            unique_together={('transferencia', 'producto')},
        ),
    ]
