# Generated by Django 4.2.7 on 2025-11-07 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_empleadouser_fecha_modificacion_user_rol'),
        ('inventario', '0002_detalletransferencia_transferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='empleado_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_realizadas', to='authentication.empleadouser', verbose_name='Empleado que realizó la transferencia'),
        ),
    ]
