# Generated by Django 5.2.5 on 2025-09-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_auto_20250916_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('STOCK_MINIMO', 'Stock mínimo alcanzado'), ('INFO', 'Información'), ('ALERTA', 'Alerta'), ('TRANSFERENCIA', 'Transferencia de productos')], default='INFO', max_length=30),
        ),
    ]
