# Generated by Django 4.2.7 on 2025-10-13 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_precio'),
        ('ofertas', '0002_hacer_descripcion_opcional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('precio_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio original')),
                ('precio_con_descuento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio con descuento')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_asignados', to='ofertas.oferta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_aplicadas', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Producto en Oferta',
                'verbose_name_plural': 'Productos en Oferta',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('producto', 'oferta')},
            },
        ),
    ]
